services:
  postgres:
    image: postgres:17
    container_name: stock_postgres

    environment:
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: stock_market

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: